version: '2'
services:
    apache2:
      image: mannionjames/apache2
      volumes:
        - ./www:/var/www/html
      expose:
        - "80"
        - "443"
    php55-fpm:
      image: mannionjames/php55-fpm
      volumes_from:
        - apache2
      expose:
        - "9000"
    maria-db:
      image: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=spiderpig
        - MYSQL_DATABASE=myLovelyDatabase